import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Resolve project paths
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const frontendPublicDir = path.join(rootDir, 'frontend', 'public');

const SITE_DOMAIN = 'https://visarank.com';
const CURRENT_DATE = new Date().toISOString().split('T')[0]; // e.g. "2026-08-15"

interface SitemapEntry {
  loc: string;
  lastmod: string;
  changefreq: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  priority: string;
}

async function generateSitemap() {
  console.log('🚀 Starting VisaRank Sitemap & Robots.txt generation...');

  // 1. Load Tracks
  const { TRACKS_DATA } = await import('../shared/src/data/tracks.ts');
  const trackIds = Object.keys(TRACKS_DATA);
  console.log(`📦 Loaded ${trackIds.length} Professional Tracks`);

  // 2. Load Visas from Shared and Frontend Registry
  const { ALL_COUNTRY_VISAS } = await import('../shared/src/data/visas.ts');
  const { PATHWAYS_REGISTRY } = await import('../frontend/src/data/visaRegistryData.ts');

  // Gather all unique visa IDs
  const allVisaIds = new Set<string>();
  ALL_COUNTRY_VISAS.forEach((v) => allVisaIds.add(v.id));
  Object.keys(PATHWAYS_REGISTRY).forEach((id) => allVisaIds.add(id));
  console.log(`📋 Loaded ${allVisaIds.size} Unique Visa Pathways`);

  const sitemapEntries: SitemapEntry[] = [];

  // 1. Level 1 Homepage
  sitemapEntries.push({
    loc: `${SITE_DOMAIN}/#/`,
    lastmod: CURRENT_DATE,
    changefreq: 'daily',
    priority: '1.0',
  });

  // 2. Level 2 Tracks Category Pages
  trackIds.forEach((trackId) => {
    sitemapEntries.push({
      loc: `${SITE_DOMAIN}/#/tracks/${trackId}`,
      lastmod: CURRENT_DATE,
      changefreq: 'weekly',
      priority: '0.9',
    });
  });

  // 3. Level 3 Visa Pathway Detail Pages
  Array.from(allVisaIds).sort().forEach((visaId) => {
    sitemapEntries.push({
      loc: `${SITE_DOMAIN}/#/visas/${visaId}`,
      lastmod: CURRENT_DATE,
      changefreq: 'weekly',
      priority: '0.8',
    });
  });

  // Generate XML
  const xmlContent = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
${sitemapEntries
  .map(
    (entry) => `  <url>
    <loc>${entry.loc}</loc>
    <lastmod>${entry.lastmod}</lastmod>
    <changefreq>${entry.changefreq}</changefreq>
    <priority>${entry.priority}</priority>
  </url>`
  )
  .join('\n')}
</urlset>
`;

  // Ensure public directory exists
  if (!fs.existsSync(frontendPublicDir)) {
    fs.mkdirSync(frontendPublicDir, { recursive: true });
  }

  // Write frontend/public/sitemap.xml
  const sitemapPath = path.join(frontendPublicDir, 'sitemap.xml');
  fs.writeFileSync(sitemapPath, xmlContent.trim() + '\n', 'utf-8');
  console.log(`✅ Generated ${sitemapPath} with ${sitemapEntries.length} indexed URLs!`);

  // Generate robots.txt
  const robotsContent = `# ==============================================================================
# VisaRank Production Robots Configuration
# https://visarank.com
# ==============================================================================

User-agent: *
Allow: /
Allow: /#/
Allow: /#/tracks/*
Allow: /#/visas/*

# Disallow indexing internal admin and management paths
Disallow: /admin
Disallow: /#/admin
Disallow: /api/admin
Disallow: /api/admin/*
Disallow: /api/auth/

# Specify Sitemap location
Sitemap: ${SITE_DOMAIN}/sitemap.xml
`;

  const robotsPath = path.join(frontendPublicDir, 'robots.txt');
  fs.writeFileSync(robotsPath, robotsContent.trim() + '\n', 'utf-8');
  console.log(`✅ Generated ${robotsPath}!`);

  // Also write sitemap XML to worker/src/utils/sitemapXml.ts so worker can serve it dynamically on Cloudflare edge
  const workerUtilsDir = path.join(rootDir, 'worker', 'src', 'utils');
  if (!fs.existsSync(workerUtilsDir)) {
    fs.mkdirSync(workerUtilsDir, { recursive: true });
  }
  const workerSitemapModule = `// Auto-generated by scripts/generate-sitemap.ts - DO NOT EDIT MANUALLY
export const SITEMAP_XML = ${JSON.stringify(xmlContent.trim() + '\n')};
export const ROBOTS_TXT = ${JSON.stringify(robotsContent.trim() + '\n')};
`;
  const workerSitemapPath = path.join(workerUtilsDir, 'sitemapXml.ts');
  fs.writeFileSync(workerSitemapPath, workerSitemapModule, 'utf-8');
  console.log(`✅ Generated edge module ${workerSitemapPath}!`);
}

generateSitemap().catch((err) => {
  console.error('❌ Sitemap generation failed:', err);
  process.exit(1);
});
